[build-system]
requires = ["setuptools", "setuptools-scm", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "workflow"
authors = [{ name = "QuakeCoRE" }]
description = "Next generation workflow powered by cylc."
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version"]
dependencies = [
    # UCGMSim Dependencies
    "im_calculation @ git+https://github.com/ucgmsim/IM_calculation.git",
    "nshmdb @ git+https://github.com/ucgmsim/NSHM2022DB.git",
    "oq_wrapper @ git+https://github.com/ucgmsim/Empirical_Engine.git#subdirectory=oq_wrapper"
    "pygmt_helper @ git+https://github.com/ucgmsim/pygmt_helper.git",
    "qcore @ git+https://github.com/ucgmsim/qcore.git",
    "source_modelling @ git+https://github.com/ucgmsim/source_modelling.git",
    "velocity_modelling @ git+https://github.com/ucgmsim/velocity_modelling.git",

    # Data Formats
    "geopandas",
    "h5py",
    "pandas[parquet, hdf5]",
    "pyyaml",
    "xarray[io]"

    # Workflow Planner
    "jinja2",
    "networkx",
    "printree",
    "pyvis",

    # Numerics
    "numexpr",
    "numpy",
    "scipy",
    "shapely",

    # CLI
    "tqdm",
    "typer",

    # Misc.
    "requests", # For gcmt-to-realisation
    "schema", # For loading realisations
    "structlog", # Logging.
]

[project.optional-dependencies]
test = [
    "pytest",
]
dev = [
    "ruff",
    "deptry"
]

[project.scripts]
nshm2022-to-realisation = "workflow.scripts.nshm2022_to_realisation:app"
gcmt-to-realisation = "workflow.scripts.gcmt_to_realisation:app"
realisation-to-srf = "workflow.scripts.realisation_to_srf:app"
generate-velocity-model-parameters = "workflow.scripts.generate_velocity_model_parameters:app"
generate-velocity-model = "workflow.scripts.generate_velocity_model:app"
generate-station-coordinates = "workflow.scripts.generate_station_coordinates:app"
generate-model-coordinates = "workflow.scripts.generate_model_coordinates:app"
generate-rupture-propagation = "workflow.scripts.generate_rupture_propagation:app"
copy-domain-parameters = "workflow.scripts.copy_velocity_model_parameters:app"
create-e3d-par = "workflow.scripts.create_e3d_par:app"
generate-stoch = "workflow.scripts.generate_stoch:app"
merge-ts = "workflow.scripts.merge_ts:app"
hf-sim = "workflow.scripts.hf_sim:app"
bb-sim = "workflow.scripts.bb_sim:app"
im-calc = "workflow.scripts.im_calc:app"
check-srf = "workflow.scripts.check_srf:app"
check-domain = "workflow.scripts.check_domain:app"
plan-workflow = "workflow.scripts.plan_workflow:app"
gcmt-auto-simulate = "workflow.scripts.gcmt_auto_simulate:app"
import-realisation = "workflow.scripts.import_realisation:app"

[tool.setuptools.package-dir]
workflow = "workflow"




[tool.setuptools_scm]


[tool.ruff.lint]
extend-select = [
    # isort imports
    "I",
    # Use r'\s+' rather than '\s+'
    "W605",
    # All the naming errors, like using camel case for function names.
    "N",
    # Missing docstrings in classes, methods, and functions
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    # Use f-string instead of a format call
    "UP032",
    # Standard library import is deprecated
    "UP035",
    # Missing function argument type-annotation
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN205",
    "ANN206",
    # Using except without specifying an exception type to catch
    "BLE001",
]
ignore = ["D104"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
known-first-party = [
    "source_modelling",
    "workflow",
    "pygmt_helper",
    "qcore",
    "empirical",
    "nshmdb",
    "IM",
    "mera",
    "velocity_modelling",
]

[tool.ruff.lint.per-file-ignores]
# Ignore no docstring in __init__.py
"__init__.py" = ["D104"]
# Ignore docstring errors in tests folder
"tests/**.py" = ["D"]

[tool.coverage.run]
omit = ["workflow/scripts/*.py"]

[tool.numpydoc_validation]
checks = [
    "GL05",
    "GL08",
    "GL10",
    "PR01",
    "PR02",
    "PR03",
    "PR04",
    "PR05",
    "PR06",
    "PR07",
    "RT01",
    "RT02",
    "RT03",
    "RT04",
    "YD01",
]
# remember to use single quotes for regex in TOML
exclude = [ # don't report on objects that match any of these regex
    '\.undocumented_method$',
    '\.__repr__$',
]
