[root]
platform = "rch-slurm"

[root.environment]
CONTAINER = "/scratch/projects/rch-quakecore/containers/runner_latest.sif"

[im_calc.environment]
KO_MATRIX_PATH = "/scratch/projects/rch-quakecore/ko_matrices"

[copy_input]
platform = "localhost"

[copy_domain_parameters]
platform = "localhost"

[create_e3d_par]
platform = "localhost"

[emod3d.directives]
--ntasks = 160
--mem-per-cpu = "2000MB"
--time = "06:00:00"

[gcmt_to_realisation]
platform = "localhost"

[generate_station_coordinates]
platform = "localhost"

[generate_velocity_model.directives]
--cpus-per-task = 64
--time = "03:00:00"

[hf_sim.directives]
--cpus-per-task = 32
--time = "01:00:00"

[im_calc.directives]
--cpus-per-task = 64
--time = "01:00:00"
--mem = "100G"

[nshm_to_realisation]
platform = "localhost"
