name: CI
on:
  pull_request:
  push:
    branches: [pegasus]

jobs:
  ci:
    uses: ucgmsim/meta-ci-action/.github/workflows/ci.yml@v2
    with:
      system-packages: "gmt libgmt-dev ghostscript"
      enable-coverage: true
      cov-package: workflow
      cov-fail-under: 95
