name: CI
on: [pull_request]

jobs:
  ci:
    uses: ucgmsim/meta-ci-action/.github/workflows/ci.yml@v1
    with:
      package-dir: workflow
      system-packages: "gmt libgmt-dev ghostscript"
      enable-coverage: true
      cov-package: workflow
      cov-fail-under: 95
