name: Deptry Dependency Check

on: [push, pull_request]

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup the minimum required python distribution
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # Install deptry
      - run: pip install deptry
      # Remove pyproject.toml so that deptry doesn't get confused
      - run: rm pyproject.toml
      # Run deptry to check that all dependencies are present.
      - run: deptry .
