name: Pytest Check
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install GMT
        run: sudo apt-get update && sudo apt-get install -y gmt libgmt-dev ghostscript
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
      - run: uv venv
      - run: uv pip install -e ".[test,dev]"
      # - name: Download velocity data
        # shell: bash -l -e {0}
        # run: uv run nzcvm-data-helper ensure --no-full
      - name: Download velocity data
        run: uv run nzcvm-data-helper ensure --no-full
      - name: Run tests
        run: uv run pytest --cov=workflow --cov-report=html tests
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
          include-hidden-files: true
          if-no-files-found: ignore
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
      - name: Install coverage tool
        run: uv tool install coverage[toml]
      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-data
      - name: Combine coverage and fail it it's under 100 %
        run: |
          uv tool run coverage html --skip-covered --skip-empty
          # Report and write to summary.
          uv tool run coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY
          # Report again and fail if under 95%.
          uv tool run coverage report --fail-under=95
      - name: Upload HTML report if check failed
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
        if: ${{ failure() }}
